title: Jeopardy!
description: >-
  Jeopardy, with Jekyll!
url: ""

collections:
  boards:
    output: true

plugins: []

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
